before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: IyiyEwF1mwr6zgbstM+PaYzYbIIcZlwCVIQAz35L+I9hYByBZSubamvEQQ48EVyY1YIsNdfvEq+JwdFo0sypofk/GxdzVxxEWzRliM/ZzoZjFnbjS9PQqji8APn6OkPYMw/ac2Jg1B3YaH1OzWAs0GZCepZ6on94W5e6mctKn9s= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: ODA3ZjNjZjcxMDI5MDg0MGZlNTU5MzViZmMyMzA0ZDE=lRJfwhlmVyNWNhuku7AtguysAzidxfgqti+92YG+Yl5T7roOKxz41seoe+EfbESEHqdtYmwF51NRQunCSqLzEE/xx1mDYYOrxQkVHkGX0Wzee1b5PcVWEZHtnB01m6R8Dkun0VQ232jXqCbUAnsQj6nyeytvzZ+UTe9Z1A8xd7ORc8PglcZJavqcFtX3qdwE1fmkHEVEQiTsaX7jUiWiMoyU9CweSZRp5NTfxIvi7FAqkeohNIfkBVr9ep95e2JAAbH4LbacIObird2tczHcc15u726OILnhS2InPgj2gBo6qEW4P76mj4jPobO/boUKvp8eT8s1Mprs+Iq8FJBZnZyOitKxHIqj4r6O/JMZfEPKLa52SFCgdcLPfBdVuPX30ECSP4SjpxcqqFBxE5MT0jLLM4bzgz5/nI4XioBB2vRdu2o3CUrk68vQMStf/uKnrjlzBp1OT0+ZROdMmAD2lMNsA5yDoF7kFZlFZlIA2f6B5MNTPMtU8t8lEn4RybLRcjyfh4soVeFiKUC0TlCEi0CPZyFaMpYY/8vh/r+Om4MLV981yB+8na8bU7MjI4bG7lbBw//9oVhkrW/RUaPEKYiv8UQHBOBWfCVPjmjGJjse+39Ngz93bA7GFoCu5cUdE5lbusYwYsr8JqXsE5f+2VYLA4K8v3xnAGMm0x3s01dHLMs/Wt3HNmTnpozL1DUcL283fRU9vKUShSoS80HEBrvmyZiChddq7cNtzyplw3GbVYPpuIFExw3IsH6Iq2djFX4fidUSUHbSefDW8/AKcaXZaO2Phh2qU1CWuWIe7ARqqKluS6w/AOPHDB/aDEihvQ0NMSSqlkN/sG8gShdW/c5NXRuB7t5ubKf+pjf20h5hNPG6QSQkL/cAq2NWvR1fMQGkhHEVIg7VLqfhD2jUkDytZHzQP39+Zit4Ko0YpOhFANvpf552SsCH7lazTiII8ltI0crAca2zlyBVe23FKogO8pEqkPILqusAQr/uYWdBY4PCcBPrsFyjKTOzIduSj1ZpmUsFA6X0CAg9HjtOLvsVwvqHNtC/rH0FeTaA9Q6GWE3z13yLl111gS8fHkv1I1L/69uIU2/eMFchEibkhYbtRBnu5Gg4skr+YwX8o+4yZncK3l7cnbOBE9W49Y7NwA8kRDwOT9ikusiZ/0MZEUJvEhauoGnfhflx9qHA+gcdTKA86ADjRz0DbdKL/R15lfwiFxcYzio6DzlRb4GtdqkrcYsUEB7Kuz6v8rQgoVunF25LaBY/UvtI/MGJcchf2SM+fFE0CqF61GFIzah52mqAqc80J8HxOFOKkKRTzwo9LgpNLR6yavckxHJ/A7mE2EIjdye/VV1YvVJnxSl9lAWJ0LMDh4hADHjaB+dihWGUxAFkWpVeeL7fYxfPq725m5XJi8zQqw6RhcX6qKmNLB3UocdgsslWoUYJVh7oMD0= # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
