before_install:
  ## init xvfb
  ## http://docs.travis-ci.com/user/gui-and-headless-browsers/
  - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
  only:
  - browser
  - master
  - npm
  - unstable
env:
  global:
  ## AES_256_KEY
  - secure: L4pFPTRxjJJYJomGUxQKxQFtb3iH/+c38VqxglZ+XP6UTzmEMmwPN/28u0Jj6v4GhIH5USHJnIBFxnJo4ygmj1Ikxk0njnE5AUpExM54bE39KDV47kCYP+uOmkFRVlyremrRrYFBDVvMKw5nvtT7s5uDgly6BFjc/VVLdlh1EAg=
language: node_js
node_js:
- '0.10'
script:
  - ./utility2.sh ci-build
