## before_script:
  ## - psql -c "create database travis_ci_test;" -U postgres
  ## - export POSTGRES_URL=postgres://localhost/travis_ci_test
## use darwin platform
language: objective-c
## language: node_js
## node_js:
  ## - "0.10"
## script: export PATH=$(./utility2.sh npmInstall) && npm install && npm test
script: ./utility2.sh --utility2-build-travis

